Wrk 41 active contracts only
flock-community/flock-eco-workday pull request #282
Opened 2023-01-13 13:24 UTC by Fputker

Nieuw scherm voor Actieve contracten

2023-01-20 11:02 UTC, timsmelik requested changes

2023-01-20 13:29 UTC, Fputker commented on src/main/react/clients/ContractClient.ts
> +export type ContractRequest = {};
The only thing I fixed is the spelling. The lack of types inside has been there for a while...

I guess the only common thing in the contract request is a `from` and a nullable `to`. We could add those here, but I am not sure what the repercussions are.

2023-01-20 13:38 UTC, Fputker commented on src/main/react/features/person/table/PersonTableHead.tsx
> +    align: false,
true, done.

2023-01-20 13:45 UTC, Fputker commented on src/main/react/features/report/Contract/ContractReportTable.tsx
> +      <CardHeader
Removing the tag from around tge <CardHeader> tag gives me the following error: 
TS2657: JSX expressions must have one parent element.

2023-01-20 13:46 UTC, Fputker commented on src/main/react/features/report/Contract/ContractReport.tsx
> +  return <Grid item xs={12}>
done

2023-01-20 13:47 UTC, Fputker commented on src/main/react/features/report/Contract/ContractReportTableHead.tsx
> +    align: false,
done

2023-01-20 13:47 UTC, Fputker commented on src/main/react/features/report/Contract/ContractReportTable.tsx
> +          // labelDisplayedRows={() => null}
done

2023-01-24 14:25 UTC, wilmveel approved these changes

2023-01-25 10:59 UTC, Fputker commented on src/main/react/features/report/Contract/ContractReportTable.tsx
> +      <CardHeader
Willem explained what you mean. I've updated this

2023-01-25 11:03 UTC, merged